apiVersion: apps/v1
kind: Deployment
metadata:
  name: waha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waha
  template:
    metadata:
      labels:
        app: waha
    spec:
      containers:
        - name: waha
          image: devlikeapro/waha:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: waha
spec:
  selector:
    app: waha
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
